# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default='Wstęp do posta', max_length=140),
        ),
    ]
