# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Author', max_length=30),
        ),
    ]
